#!/usr/bin/env bash

# Don't change this line
#===========================================
name_rom=$(grep init $CIRRUS_WORKING_DIR/build.sh -m 1 | cut -d / -f 4)
branch_name=$(grep init $CIRRUS_WORKING_DIR/build.sh | awk -F "-b " '{print $2}' | awk '{print $1}')
BUILDLOG=$WORKDIR/rom/$name_rom/build.log
DEPIS=$(grep lunch $CIRRUS_WORKING_DIR/build.sh -m 1 | cut -d ' ' -f 2 | cut -d _ -f 2 | cut -d - -f 1)
grep _jasmine_sprout $CIRRUS_WORKING_DIR/build.sh > /dev/null && DEPIS=jasmine_sprout
grep _laurel_sprout $CIRRUS_WORKING_DIR/build.sh > /dev/null && DEPIS=laurel_sprout
grep _GM8_sprout $CIRRUS_WORKING_DIR/build.sh > /dev/null && DEPIS=GM8_sprout
grep _maple_dsds $CIRRUS_WORKING_DIR/build.sh > /dev/null && DEPIS=maple_dsds
DISTRO=$(source /etc/os-release && echo "${PRETTY_NAME}")

TERM=xterm
red=$(tput setaf 1)             #  red
grn=$(tput setaf 2)             #  green
blu=$(tput setaf 4)             #  blue
cya=$(tput setaf 6)             #  cyan
txtrst=$(tput sgr0)             #  Reset

timeStart() {
    DATELOG=$(date "+%H%M-%d%m%Y")
    BUILD_START=$(date +"%s")
    DATE=$(date)
}

timeEnd() {
	BUILD_END=$(date +"%s")
	DIFF=$(($BUILD_END - $BUILD_START))
}

telegram_curl() {
    local ACTION=${1}
    shift
    local HTTP_REQUEST=${1}
    shift
    if [[ "${HTTP_REQUEST}" != "POST_FILE" ]]; then
        curl -s -X "${HTTP_REQUEST}" "https://api.telegram.org/bot$TG_TOKEN/$ACTION" "$@" | jq .
    else
        curl -s "https://api.telegram.org/bot$TG_TOKEN/$ACTION" "$@" | jq .
    fi
}

telegram_main() {
    local ACTION=${1}
    local HTTP_REQUEST=${2}
    local CURL_ARGUMENTS=()
    while [[ "${#}" -gt 0 ]]; do
        case "${1}" in
            --animation | --audio | --document | --photo | --video )
                local CURL_ARGUMENTS+=(-F $(echo "${1}" | sed 's/--//')=@"${2}")
                shift
                ;;
            --* )
                if [[ "$HTTP_REQUEST" != "POST_FILE" ]]; then
                    local CURL_ARGUMENTS+=(-d $(echo "${1}" | sed 's/--//')="${2}")
                else
                    local CURL_ARGUMENTS+=(-F $(echo "${1}" | sed 's/--//')="${2}")
                fi
                shift
                ;;
        esac
        shift
    done
    telegram_curl "${ACTION}" "${HTTP_REQUEST}" "${CURL_ARGUMENTS[@]}"
}

telegram_curl_get() {
    local ACTION=${1}
    shift
    telegram_main "${ACTION}" GET "$@"
}

telegram_curl_post() {
    local ACTION=${1}
    shift
    telegram_main "${ACTION}" POST "$@"
}

telegram_curl_post_file() {
    local ACTION=${1}
    shift
    telegram_main "${ACTION}" POST_FILE "$@"
}

tg_send_message() {
    telegram_main sendMessage POST "$@"
}

tg_edit_message_text() {
    telegram_main editMessageText POST "$@"
}

tg_send_document() {
    telegram_main sendDocument POST_FILE "$@"
}

progress() {
    echo "BOTLOG: Build tracker process is running..."
    sleep 5;

    while [ 1 ]; do
        if [[ ${retVal} -ne 0 ]]; then
            exit ${retVal}
        fi

        # Get latest percentage
        PERCENTAGE=$(cat $BUILDLOG | tail -n 1 | awk '{ print $2 }')
        NUMBER=$(echo ${PERCENTAGE} | sed 's/[^0-9]*//g')

        # Report percentage to the $TG_CHAT_ID
        if [[ "${NUMBER}" != "" ]]; then
            if [[ "${NUMBER}" -le  "99" ]]; then
                if [[ "${NUMBER}" != "${NUMBER_OLD}" ]] && [[ "$NUMBER" != "" ]] && ! cat $BUILDLOG | tail  -n 1 | grep "glob" > /dev/null && ! cat $BUILDLOG | tail  -n 1 | grep "including" > /dev/null && ! cat $BUILDLOG | tail  -n 1 | grep "soong" > /dev/null && ! cat $BUILDLOG | tail  -n 1 | grep "finishing" > /dev/null; then
                echo -e "BOTLOG: Percentage changed to ${NUMBER}%"
                    if [[ "$NUMBER" == "1" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▱▱▱▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "2" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▱▱▱▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "3" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▱▱▱▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "4" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▱▱▱▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "5" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▱▱▱▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "6" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▱▱▱▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "7" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▱▱▱▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "8" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▱▱▱▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "9" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▱▱▱▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "10" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▱▱▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "11" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▱▱▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "12" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▱▱▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "13" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▱▱▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "14" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▱▱▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "15" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▱▱▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "16" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▱▱▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "17" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▱▱▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "18" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▱▱▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "19" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▱▱▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "20" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▱▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "21" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▱▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "22" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▱▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "23" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▱▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "24" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▱▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "25" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▱▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "26" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▱▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "27" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▱▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "28" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▱▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "29" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▱▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "30" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "31" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "32" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "33" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "34" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "35" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "36" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "37" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "38" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "39" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▱▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "40" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "41" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "42" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "43" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "44" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "45" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "46" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "47" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "48" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "49" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▱▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "50" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "51" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "52" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "53" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "54" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "55" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "56" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "57" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "58" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "59" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▱▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "60" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "61" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "62" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "63" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "64" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "65" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "66" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "67" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "68" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "69" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▱▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "70" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▰▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "71" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▰▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "72" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▰▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "73" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▰▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "74" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▰▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "75" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▰▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "76" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▰▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "77" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▰▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "78" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▰▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "79" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▰▱▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "80" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▰▰▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "81" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▰▰▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "82" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▰▰▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "83" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▰▰▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "84" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▰▰▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "85" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▰▰▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "86" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▰▰▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "87" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▰▰▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "88" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▰▰▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "89" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▰▰▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "90" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▰▰▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "91" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▰▰▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "92" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▰▰▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "93" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▰▰▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "94" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▰▰▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "95" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▰▰▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "96" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▰▰▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "97" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▰▰▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "98" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▰▰▱」${NUMBER}% 💨" > /dev/null
                    elif [[ "$NUMBER" == "99" ]]; then
                       build_message "🛠️ Building..." "🚀「▰▰▰▰▰▰▰▰▰▰」${NUMBER}% 💨" > /dev/null
                    fi
                fi
            NUMBER_OLD=${NUMBER}
            fi
            if [[ "$NUMBER" -eq "99" ]] && [[ "$NUMBER" != "" ]] && ! cat $BUILDLOG | tail  -n 1 | grep "glob" > /dev/null && ! cat $BUILDLOG | tail  -n 1 | grep "including" > /dev/null && ! cat $BUILDLOG | tail  -n 1 | grep "soong" > /dev/null && ! cat $BUILDLOG | tail -n 1 | grep "finishing" > /dev/null; then
                echo "BOTLOG: Build tracker process ended"
                break
            fi
        fi

        sleep 5
    done
    return 0
}

build_message() {
	if [ "$CI_MESSAGE_ID" = "" ]; then
CI_MESSAGE_ID=$(tg_send_message --chat_id "$TG_CHAT_ID" --text "<b>=== Starting Build ${name_rom} ===</b>
<b>👮 Builder Name:</b> $(cd $CIRRUS_WORKING_DIR && git log --pretty=format:'%an' -1)
<b>📝 Commit:</b> $(cd $CIRRUS_WORKING_DIR && git log --pretty=format:'%s' -1)
<b>🖥 Branch:</b> ${branch_name}
<b>📱 Device:</b> $DEPIS
<b>📟 Job:</b> $CIRRUS_CPU Paralel processing
<b>🗃 Penyimpanan:</b> 5TB
<b>📈 Digunakan:</b> 54.32GB
<b>📉 Tersisa:</b> 46.38GB
<b>⏳ Running on:</b> $DISTRO
<b>📅 Started at:</b> $DATE

<b>⚙️ Status:</b> ${1}
${2}" --parse_mode "html" | jq .result.message_id)
	else
tg_edit_message_text --chat_id "$TG_CHAT_ID" --message_id "$CI_MESSAGE_ID" --text "<b>=== Starting Build ${name_rom} ===</b>
<b>👮 Builder Name:</b> $(cd $CIRRUS_WORKING_DIR && git log --pretty=format:'%an' -1)
<b>📝 Commit:</b> $(cd $CIRRUS_WORKING_DIR && git log --pretty=format:'%s' -1)
<b>🖥 Branch:</b> ${branch_name}
<b>📱 Device:</b> $DEPIS
<b>📟 Job:</b> $CIRRUS_CPU Paralel processing
<b>🗃 Penyimpanan:</b> 5TB
<b>📈 Digunakan:</b> 54.32GB
<b>📉 Tersisa:</b> 46.38GB
<b>⏳ Running on:</b> $DISTRO
<b>📅 Started at:</b> $DATE

<b>⚙️ Status:</b> ${1}
${2}" --parse_mode "html"
	fi
}

statusBuild() {
    if [[ $retVal -eq 8 ]]; then
        build_message "Build Aborted 😡 with Code Exit ${retVal}.

Total time elapsed: $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) seconds."
        tg_send_message --chat_id "$TG_CHAT_ID_SECOND" --text "Build Aborted 💔 with Code Exit ${retVal}.
Sudah kubilang yang teliti 😡"
        echo "Build Aborted"
        tg_send_document --chat_id "$TG_CHAT_ID" --document "$BUILDLOG" --reply_to_message_id "$CI_MESSAGE_ID"
        LOGTRIM="$CDIR/out/log_trimmed.log"
        sed -n '/FAILED:/,//p' $BUILDLOG &> $LOGTRIM
        tg_send_document --chat_id "$TG_CHAT_ID" --document "$LOGTRIM" --reply_to_message_id "$CI_MESSAGE_ID"
        exit $retVal
    fi
    if [[ $retVal -eq 141 ]]; then
        build_message "Build Aborted 👎 with Code Exit ${retVal}, See log.

Total time elapsed: $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) seconds."
        tg_send_message --chat_id "$TG_CHAT_ID_SECOND" --text "Build Aborted ❌ with Code Exit ${retVal}."
        echo "Build Aborted"
        tg_send_document --chat_id "$TG_CHAT_ID" --document "$BUILDLOG" --reply_to_message_id "$CI_MESSAGE_ID"
        LOGTRIM="$CDIR/out/log_trimmed.log"
        sed -n '/FAILED:/,//p' $BUILDLOG &> $LOGTRIM
        tg_send_document --chat_id "$TG_CHAT_ID" --document "$LOGTRIM" --reply_to_message_id "$CI_MESSAGE_ID"
        exit $retVal
    fi
    if [[ $retVal -ne 0 ]]; then
        build_message "Build Error ❌ with Code Exit ${retVal}, See log.

Total time elapsed: $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) seconds."
        tg_send_message --chat_id "$TG_CHAT_ID_SECOND" --text "Build Error ❌ with Code Exit ${retVal}."
        echo "Build Error"
        tg_send_document --chat_id "$TG_CHAT_ID" --document "$BUILDLOG" --reply_to_message_id "$CI_MESSAGE_ID"
        LOGTRIM="$CDIR/out/log_trimmed.log"
        sed -n '/FAILED:/,//p' $BUILDLOG &> $LOGTRIM
        tg_send_document --chat_id "$TG_CHAT_ID" --document "$LOGTRIM" --reply_to_message_id "$CI_MESSAGE_ID"
        exit $retVal
    fi
    build_message "Build success ✅"
}

